# Generated by Django 3.1.4 on 2021-10-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('prenom', models.CharField(max_length=64)),
                ('statut', models.CharField(max_length=64)),
                ('niveau', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('prenom', models.CharField(max_length=64)),
                ('sexe', models.CharField(blank=True, max_length=12)),
                ('fonction', models.CharField(blank=True, max_length=64)),
                ('salaire', models.IntegerField()),
            ],
        ),
    ]
