# Generated by Django 3.1.4 on 2021-10-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='niveau',
            field=models.CharField(blank=True, default='Unassigned', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='statut',
            field=models.CharField(blank=True, default='Unassigned', max_length=64),
        ),
    ]
