# Generated by Django 3.1.4 on 2021-10-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0002_auto_20211023_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_open', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('us_open', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('tot_gal', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('total_apports', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('total_depenses', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('auth_user', models.CharField(blank=True, default='NA', max_length=64)),
                ('prevu_gd', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('prevu_us', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('etat_caisse', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
