# Generated by Django 3.1.4 on 2021-10-25 23:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0003_caisse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='etat_caisse',
            field=models.CharField(blank=True, default='Not Defined', max_length=32),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='prevu_gd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='prevu_us',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
