# Generated by Django 3.1.4 on 2021-10-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0005_auto_20211027_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='heure_ouv',
            field=models.DateTimeField(blank=True, default='2021-01-01'),
        ),
    ]
