# Generated by Django 3.1.4 on 2021-10-29 14:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0006_caisse_heure_ouv'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='ap_meter',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='caisse',
            name='av_meter',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
