# Generated by Django 3.1.4 on 2021-10-29 16:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0008_auto_20211029_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='gd_close',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='caisse',
            name='us_close',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
