# Generated by Django 3.1.4 on 2021-10-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0010_caisse_cur_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='caisse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaisse', to='topgaz.caisse'),
        ),
    ]
