# Generated by Django 3.1.4 on 2021-10-30 02:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0011_auto_20211029_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='cur_price',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=7),
        ),
    ]
