# Generated by Django 3.1.4 on 2021-10-31 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0014_vente_totalv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='tot_gal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=7),
        ),
    ]
