# Generated by Django 3.1.4 on 2021-11-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0015_auto_20211031_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='heure_close',
            field=models.DateTimeField(blank=True, default='2021-01-01'),
        ),
    ]
