# Generated by Django 3.1.4 on 2021-11-01 22:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0016_caisse_heure_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('comment', models.CharField(blank=True, default='Not defined', max_length=128)),
                ('type', models.CharField(blank=True, default='Not defined', max_length=32)),
                ('uschange', models.IntegerField(blank=True, default=0)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='topgaz.caisse')),
            ],
        ),
    ]
