# Generated by Django 3.1.4 on 2021-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0017_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='uschange',
            new_name='equiht',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tdj',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
