# Generated by Django 3.1.4 on 2021-11-06 02:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0018_auto_20211103_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='montantus',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
