# Generated by Django 3.1.4 on 2021-11-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0019_transaction_montantus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, default='Not defined', max_length=32),
        ),
    ]
