# Generated by Django 3.1.4 on 2021-11-07 04:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0021_auto_20211107_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='tot_ventes',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=7),
        ),
    ]
