# Generated by Django 3.1.4 on 2021-11-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0022_caisse_tot_ventes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tauxdujour', models.IntegerField(blank=True, default=0)),
                ('prixgallon', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
