# Generated by Django 3.1.4 on 2021-12-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0025_parametre_time2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='groupe',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
