# Generated by Django 3.1.4 on 2021-12-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0027_remove_employe_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='groupe',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
