# Generated by Django 3.1.4 on 2021-12-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0029_employe_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='fonction',
        ),
        migrations.AddField(
            model_name='employe',
            name='fposte',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
