# Generated by Django 3.1.4 on 2021-12-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0032_auto_20211206_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='email',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
