# Generated by Django 3.1.4 on 2021-12-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0036_auto_20211207_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
