# Generated by Django 3.1.4 on 2021-12-10 05:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0038_auto_20211210_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='grille',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.ManyToManyField(to='topgaz.Poste'),
        ),
    ]
