# Generated by Django 3.1.4 on 2021-12-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0040_auto_20211211_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.ManyToManyField(related_name='fonction', to='topgaz.Poste'),
        ),
    ]
