# Generated by Django 3.1.4 on 2021-12-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0041_auto_20211211_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='poste',
        ),
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonction', to='topgaz.poste'),
        ),
    ]
