# Generated by Django 3.1.4 on 2021-12-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0042_auto_20211211_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_compagnie', models.CharField(max_length=128)),
                ('adresse', models.CharField(blank=True, default='Non Defini', max_length=128)),
                ('telephone1', models.CharField(blank=True, default='Non Defini', max_length=32)),
                ('telephone2', models.CharField(blank=True, default='Non Defini', max_length=32)),
                ('email', models.EmailField(blank=True, default='Non Defini', max_length=32)),
                ('statut', models.CharField(blank=True, default='Actif', max_length=16)),
            ],
        ),
    ]
