# Generated by Django 3.1.4 on 2021-12-28 18:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0044_auto_20211214_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='nberr',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='email',
            field=models.EmailField(blank=True, default='Non Defini', max_length=64),
        ),
    ]
