# Generated by Django 3.1.4 on 2021-12-29 02:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0045_auto_20211228_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='flagged',
            field=models.CharField(blank=True, default='NON', max_length=8),
        ),
        migrations.AddField(
            model_name='vente',
            name='perte',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=7),
        ),
    ]
