# Generated by Django 3.1.4 on 2022-01-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0046_auto_20211229_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='etat_caisse',
            field=models.CharField(blank=True, default='FERME', max_length=32),
        ),
    ]
