# Generated by Django 3.1.4 on 2022-01-04 04:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0047_auto_20220103_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='ecart_gd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='caisse',
            name='ecart_us',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
    ]
