# Generated by Django 3.1.4 on 2022-01-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0049_auto_20220110_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='heure_close',
            field=models.DateTimeField(blank=True, default='2000-01-01'),
        ),
    ]
