# Generated by Django 3.1.4 on 2022-01-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0050_auto_20220110_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='timet',
            field=models.DateTimeField(blank=True, default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='vente',
            name='timev',
            field=models.DateTimeField(blank=True, default='2000-01-01'),
        ),
    ]
