# Generated by Django 3.1.4 on 2022-01-17 23:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0051_auto_20220112_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(blank=True, default='Non Defini', max_length=64)),
                ('secteur', models.CharField(blank=True, default='Non Defini', max_length=128)),
                ('adresse', models.CharField(blank=True, default='Non Defini', max_length=128)),
                ('tel_client', models.CharField(blank=True, default='Non Defini', max_length=64)),
                ('nom_contact', models.CharField(blank=True, default='Non Defini', max_length=64)),
                ('prenom_contact', models.CharField(blank=True, default='Non Defini', max_length=128)),
                ('tel_contact', models.CharField(blank=True, default='Non Defini', max_length=64)),
                ('solde', models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=7)),
            ],
        ),
    ]
