# Generated by Django 3.1.4 on 2022-01-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0053_auto_20220118_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom_client',
            new_name='nom_compagnie',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='tel_client',
            new_name='telephone',
        ),
    ]
