# Generated by Django 3.1.4 on 2022-02-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0056_vente_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='type',
            field=models.CharField(blank=True, default='CASH', max_length=8),
        ),
    ]
