# Generated by Django 3.1.4 on 2022-02-03 01:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topgaz', '0057_vente_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timev', models.DateTimeField(blank=True, default='2000-01-01')),
                ('type', models.CharField(blank=True, default='Non Defini', max_length=16)),
                ('montant', models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=7)),
                ('solde', models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.00'), max_digits=7)),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='topgaz.client')),
            ],
        ),
    ]
