# Generated by Django 3.1.1 on 2020-09-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=64)),
                ('nom', models.CharField(max_length=64)),
                ('phone1', models.CharField(max_length=32)),
                ('phone2', models.CharField(max_length=32)),
                ('adresse', models.CharField(max_length=128)),
                ('mail', models.CharField(max_length=64)),
                ('niveau', models.CharField(max_length=32)),
            ],
        ),
    ]
