# Generated by Django 3.1.1 on 2020-09-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proligaz', '0003_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField()),
                ('heure_achat', models.TimeField()),
                ('commentaire', models.CharField(default='No Comment', max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acheteurs', to='proligaz.clients')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='proligaz.produits')),
            ],
        ),
    ]
