# Generated by Django 3.1.1 on 2020-09-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proligaz', '0005_auto_20200924_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='adresse',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='clients',
            name='mail',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='clients',
            name='niveau',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone2',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
