# Generated by Django 3.1.1 on 2020-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proligaz', '0006_auto_20200924_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventes',
            name='commentaire',
            field=models.CharField(blank=True, default='No Comment', max_length=128),
        ),
    ]
