# Generated by Django 3.1.1 on 2020-09-30 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proligaz', '0007_auto_20200924_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poste', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=64)),
                ('nom', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=128)),
                ('salaire_base', models.IntegerField(blank=True)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postevendeur', to='proligaz.poste')),
                ('prod_vendus', models.ManyToManyField(blank=True, related_name='vendeur', to='proligaz.Produits')),
            ],
        ),
    ]
