# Generated by Django 3.1.1 on 2020-10-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proligaz', '0009_auto_20200930_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='salaire_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
        ),
    ]
