# Generated by Django 3.1.1 on 2020-10-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proligaz', '0010_auto_20201001_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
