# Generated by Django 3.1.1 on 2020-10-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proligaz', '0011_auto_20201005_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remplissage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_rempl', models.DateTimeField(blank=True, default='2020-06-10 00:14')),
                ('compt_debut', models.DecimalField(decimal_places=1, max_digits=6)),
                ('compt_avant', models.DecimalField(decimal_places=1, max_digits=6)),
                ('achat_pour', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('quantite', models.DecimalField(decimal_places=1, max_digits=6)),
                ('compt_apres', models.DecimalField(decimal_places=1, max_digits=6)),
                ('px_gallon', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('compt_fin', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
    ]
