# Generated by Django 3.1.1 on 2020-10-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proligaz', '0013_remove_remplissage_heure_rempl'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplissage',
            name='heure_rempl',
            field=models.DateTimeField(blank=True, default='2020-06-10 00:14'),
        ),
    ]
