# Generated by Django 3.1.1 on 2020-10-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proligaz', '0014_remplissage_heure_rempl'),
    ]

    operations = [
        migrations.AddField(
            model_name='remplissage',
            name='type_pay',
            field=models.CharField(blank=True, default='NA', max_length=32),
        ),
        migrations.AlterField(
            model_name='remplissage',
            name='compt_fin',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6),
        ),
    ]
